### ISSUE TITLE
[BORK] Parrots throw a giant party at spawn

### ISSUE THREAD

**Issue by sibraxlis** [AuroraInteractive/network-script-data#21]
> **Describe the bug**:
Parrots don't follow you when you leave the survival spawn.

> **How To Reproduce**:
bring parrots to spawn from behrcraft

> **Expected behavior**:
parrots leave with you.

**Comment by BehrRiley** [comment]
> **How To Reproduce:**
> bring parrots to spawn from behrcraft
To verify, you're replicating this by obtaining Parrots on Behrcraft, and then leaving to an external server via `/play` and that entity follows you through the bungee server?

**Comment by sibraxlis** [comment]
Pol was the one it happened to i believe. I was told it was his parrot pile in the old world.

**Comment by sibraxlis** [comment]
There was like a 15 parrot pile by the stables

**Comment by BehrRiley** [comment]
Again, just need clarification that you're saying parrots are following players from the server `Behrcraft` to a completely different server: `survival` please

**Comment by BehrRiley** [comment]
Can't reproduce and additionally, I don't believe entities can cross servers, that kind of information isn't saved and passed to other servers.
