### ISSUE TITLE
Scripts to add to hub.

### ISSUE THREAD

**Issue by sibraxlis** [AuroraInteractive/network-script-data#24]
~~Can’t place blocks~~
~~Can’t break blocks~~
~~Negates fall damage~~
Edit:
Need to create handlers for when unauthorized players are trying to do things they shouldn't in each applicable server Spawn.

**Script Events**:
- [x] `player places block` | Prevent players from placing blocks
- [x] `player breaks block` | Prevent players from breaking the spawn
- [x] `player damaged by:fall` | Prevent players from taking fall damage
- [x] `player changes food level` | Prevents players from starving
- [x] `player changes air level` | Prevent players from drowning
- ~~`player combusts` | Prevents players from combusting into flames...~~

And, if applicable:
- [ ] `player damages vehicle` | Prevents players from breaking minecarts, boats
- [ ] `player destroys vehicle` | Prevents players from destroying minecarts, boats
- [x] `player breaks hanging` | Prevents players from destroying item frames, paintings
- [ ] `player changes block` | Prevents players from changing block materials, eg stomping on farmland
- [x] `player creates portal` | Prevents players from creating nether portals if the blocks exist to create one
- [ ] `player interacts with block` | Prevents players from interacting with buttons, levers etc

**Comment by BehrRiley** [comment]
This appears to be finished now.

**Comment by Eutherin** [comment]
Not done.
![image](https://user-images.githubusercontent.com/25861695/90507957-a0fc4a80-e10b-11ea-8368-ef730c478da3.png)
