### ISSUE TITLE
Consider survival name coloring change

### ISSUE THREAD

**Issue by sibraxlis** [AuroraInteractive/network-script-data#26]
![image](https://user-images.githubusercontent.com/25861695/89718732-1d599580-d976-11ea-86e3-92a58df1eb56.png)
Looks really weird as its formatted.

**Comment by pjochillin** [comment]
I fixed this by modifying the server's display_name flag (see attached for modification).
![image](https://user-images.githubusercontent.com/30186714/89720251-07f86180-d99e-11ea-8370-dc9d80064d15.png)
