### ISSUE TITLE
[BORK] /home not working

### ISSUE THREAD

**Issue by Mutim** [AuroraInteractive/network-script-data#32]
> **How To Reproduce**:
type /home

> **Expected behavior**:
Teleport you to your home.

> **Screenshots**:

> **Additional context**:
Might be related to the duplicate characters.

**Comment by Mutim** [comment]
Affected code: 
survival\repo-link\sethome.dsc

Affected line:
line 21

**Comment by sibraxlis** [comment]
working for me

**Comment by Mutim** [comment]
made new home here, and then used the raw teleport <location[home_<player.uuid>]>
And that moved me back. 
/home works as well. 

For some reason, my home was corrupt. Making a new home "fixes" it (not really, just puts a bandage on it)
