### ISSUE TITLE
[BORK] Home on death does not give damage resistance

### ISSUE THREAD

**Issue by Eutherin** [AuroraInteractive/network-script-data#35]
> **Describe the bug**:
You can repeatedly fall to your death if your home is suddenly in the air.

> **How To Reproduce**:
sethome in air, or have a location which was once on the ground but is now say 100 blocks in the air where a dungeon shop used to be.
Die
Hit respawn

> **Expected behavior**:
Not falling to my death immediately lol.

> **Suggested Fix**
10s of fall damage immunity on respawn

**Comment by pjochillin** [comment]
I added a 10s damage immunity (from everything) on respawn, refer to PR #25 on Behr's fork.
