### ISSUE TITLE
[Borked] Holograms stay when graves pop

### ISSUE THREAD

**Issue by Eutherin** [AuroraInteractive/network-script-data#54]
I've attached an image below that shows that holograms seem to stay when graves pop. My guess is it's maybe because the chunk was unloaded when the time expired? i'm not sure. Here's the image: ![img](https://cdn.discordapp.com/attachments/626080540638052382/744816063249907722/unknown.png)

**Comment by Ph4i1ur3** [comment]
Pushed a potential fix for this.
